### ISSUE TITLE
Update to new Authentication system

### ISSUE THREAD

**Issue by rrbarry11** [marckrenn/framer-Firebase#11]
With the more recent changes to the Firebase system, they have depreciated the 'Database Secret' used to authenticate users. Instead they link you here: [Firebase Admin SDK](https://firebase.google.com/docs/admin/setup?authuser=0) 

Any chance you could adjust the module to allow for this new authentication system?

Thanks for the hard work!

**Comment by marckrenn** [comment]
Yup, it's depreciated, but you can still use it, right?

I plan to stick with the current 'Database Secret'-authentication method for another 2-3 and then I'll re-evaluate the situation.

**Comment by rrbarry11** [comment]
Yes I can still use it and sounds good to me!
