### ISSUE TITLE
Firebase update broke the module.

### ISSUE THREAD

**Issue by akawizzard** [marckrenn/framer-Firebase#12]
Recent Firebase update (Probably GDPR related) now require a proper authentication of users. Simple "secret" and project ID doesn't work anymore :(

**Comment by marckrenn** [comment]
My example projects are still working fine for me, as are newly created Firebase projects.

Could you link me to your non-working example?

**Comment by akawizzard** [comment]
Wow, looks like it works again today, sorry for bothering you. Maybe it was just a fluke in Firebase yesterday.

**Comment by marckrenn** [comment]
No problem :)
