### ISSUE TITLE
Beginner Question: How do I set the value of a global variable with returned data?

### ISSUE THREAD

**Issue by nickperdomo** [marckrenn/framer-Firebase#13]
I'd like to use returned data outside of the get function. I tried the following, but the scope of `window.deadlines` appears to be limited to the get function.
```coffeescript
window.deadlines = []

firebase.get "/#{framerProject}/deadlines", (data) ->
	window.deadlines = data

print window.deadlines # prints 'undefined'
```

**Comment by marckrenn** [comment]
Hi there,

that's not going to work, as the `print window.deadlines` executes before the asynchronous `firebase.get`-callback. If you put `print window.deadlines` inside of the `firebase.get` callback, it should work. 

Put anything that you want to do with the deadlines into the aforementioned callback.

Let me know if that helped :)

**Comment by nickperdomo** [comment]
@marckrenn Thank you for confirming. Awesome work here!
