### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by marckrenn** [marckrenn/framer-Firebase#3]
1. Move from Firebase REST API to Javascript API
2. Add additional features provided by Javascript API (DB changes when connection is lost, user authentication etc.) 
3. Provide zero-setup public and private database (latter would require some sort of login-frontend)
4. Rewrite with Query-function
5. Fix Auto-Refresh incompatibility

**Comment by mlaurita** [comment]
Hey Marc,

Any way you could add methods for goOnline() and goOffline()? I'm reaching my simultaneous connection limit on firebase with just me using the prototype and I have no idea why. Having manual control might solve the issue? 

If you have a solution for this already, I'd love to hear it. Thx!

**Comment by bredowmax** [comment]
Hi Marc,
I would love to have user authentication on my prototype! Just saw you already have it on your roadmap

**Comment by marckrenn** [comment]
Yeah, authentication would be cool, but right now its probably not possible to implement for various reasons. One being, that OAuth2-flows (via popups) are currently not supported from within Framer.

I'll re-evaluate this in mid18.
