### ISSUE TITLE
Firebase didn't put after 3 or 4 times

### ISSUE THREAD

**Issue by bomho** [marckrenn/framer-Firebase#6]
Hi I'm Bomho.Lee from designer in Coupang.

Though your firebase module for framer, 
whenever i tap the button, I want to put my database in coffeescript.
but after 3 or 4 times, firebase didn't put anything.

Link here [https://framer.cloud/XNURW](url)

Please, Check about this.
Thanks.

**Comment by marckrenn** [comment]
Hey Bomho,

Does [this](https://framer.cloud/ppESJ) solve the problems you're seeing?

**Comment by bomho** [comment]
Not yet, i’ll try after holiday~ :)
there is big holiday “chusuk” in Korea 

i’ll let you know~

DESIGNER BomHo. Lee              M leebomho@gmail.com                   P +82) 10-8876-0315

2017. 9. 29. 오후 8:50, Marc Krenn <notifications@github.com> 작성:

**Comment by ochanje210** [comment]
happy Chusuk! :)
