### ISSUE TITLE
Occasional Syntax Error / JSON unexpected EOF 

### ISSUE THREAD

**Issue by songcarver** [marckrenn/framer-Firebase#7]
Thanks for understanding my n00bness…

My prototype is occasionally get **SyntaxError : JSON Parse error; Unexpected EOF** which seems to happen when network disappears. Wondering if anyone else is seeing this, and if they know where it's happening? 

It seems to be happen at
    callback(JSON.parse(xhttp.responseText)) if callback?

I've tried writing conditionals to only try doing GET and PUT etc when connected and to check that the functions actually return a non-null thing.

AFAICT the responseText might not be valid formed JSON which throws an error?

**Comment by marckrenn** [comment]
Hey @songcarver,
thanks for reporting this problem. Without having replicated this behavior yet, I think this is caused by `JSON.parse` trying to parse `xhttp.responseText` of `null` or `undefined`. I just pushed an update that should fix it.

Could you please verify if it does?

Thanks.

**Comment by songcarver** [comment]
Thanks! I'm trying it out. 

I did a little hacking earlier and made a version with a try/catch which also seemed to fix the issue. Will let you know if your official fix produces any more errors. 

Thanks for the quick turnaround. It is a really cool tool.

**Comment by songcarver** [comment]
Hmm I seemed to have got the same issue with your change. Here's the change I'd made which *seems* to not produce the error:

```				when 4
                    try 
                        callback(JSON.parse(xhttp.responseText)) if callback?
                    catch e
                        console.log e
```

**Comment by marckrenn** [comment]
Wrapping it into try/catch seems like a good idea, thank you.

Do you want to create a PR?

**Comment by songcarver** [comment]
I can try!
